### ISSUE TITLE
points for improvement

### ISSUE THREAD

**Issue by bvreede** [esciencecenter-digital-skills/good-practices-in-research-software-development#10]
- [ ] #25
- [ ] describe in instructor notes: one project taken through the entire course
- [ ] describe in instructor notes: take ample time for the final exercise
- [x] describe in instructor notes: documentation as demo
- [ ] add slides as improved by Ole, Barbara, Luisa, Dani
- [ ] add modularity exercise, improvement: clearer instructions on the exercise, namely: behavior of the function should not change. Perhaps info on how to check this.
- [ ] add more material on docstrings

**Comment by lyashevska** [comment]
- [x] edit slides as there are a couple of typos and broken links

**Comment by lyashevska** [comment]
- [ ] feed modularity exercise back to Code Refinery
