### ISSUE TITLE
Update documentation episode

### ISSUE THREAD

**Issue by JaroCamphuijsen** [esciencecenter-digital-skills/good-practices-in-research-software-development#13]
The coderefinery episode on documentation was updated, as well as the instructor notes. It no longer includes our shortened schedule "[A lesson with a focus on in-code-documentation and readme files](https://coderefinery.github.io/documentation/guide/#a-lesson-with-a-focus-on-in-code-documentation-and-readme-files)". 

This schedule can still be retrieved from the github history:

https://github.com/coderefinery/documentation/blob/077906ba8634d1b1840f804b04c895c08feff042/content/guide.md

**Comment by lyashevska** [comment]
Add to the instructor notes that sphynx is a demo.

**Comment by lyashevska** [comment]
@svenvanderburg is this adressed in #40? If so, can be closed.

**Comment by svenvanderburg** [comment]
Yes, this is addressed with #40, closing the issue.
