### ISSUE TITLE
Create a design for how slides should be organised

### ISSUE THREAD

**Issue by svenvanderburg** [esciencecenter-digital-skills/good-practices-in-research-software-development#18]
Slides are currently living in a workshop-specific separate repo in a separate organisation: https://github.com/NLeSC-slides/2023-06-19-ds-cr and work with `reveal.js`. 

Some questions I have:
1. How can we organise this better? I would at least like to have the slides live in this repository.
2. I heard not everyone is comfortable working with `reveal.js`, or that it didn't always work that well during workshops. Maybe just gossips ;) Maybe it's a matter of better documenting. Anyway, any instructor should be easily able to use and update the slides.
3. I see you have the same `files` and `reveal.js` folders inside each module, see [code modularization](https://github.com/NLeSC-slides/2023-06-19-ds-cr/tree/main/code_modularization) as example. And then the files are also the same for each module. Can we change that?

Can we make a small design (can be super simple of course)? And create some issues once at least 2 people agree (doesn't have to be me per se as long as there is a concious decision) @OleMussmann I think you know most about this?

**Comment by OleMussmann** [comment]
- [Request For Comment] Reveal.js vs PPT for teaching @lyashevska @svenvanderburg
	- Reveal.js tech stack
		- Python GUI framework to create slides and view locally
			- https://github.com/OleMussmann/reveal_launcher/
		- Write slides in markdown or HTML/CSS in your favorite editor
			- Code on GitHub
			- Push to deploy on GitHub pages
				- https://github.com/nlesc-slides
				- Needs naming convention
		- View slides and present in the browser
			- Unresolved issue: Sometimes browser cache keeps slide updates from showing
				- How to resolve?
		- Commercial site for drag&drop slide creation (not used)
			- https://slides.com/
			- Vendor lock-in
	- Steps needed to make reveal.js usable
		- Fix browser cache issue (?h)
		- Refactor code to improve quality (16h)
		- Package code (8h)
			- Which options are best for easy deployment across different OSes?
		- Write documentation and tutorial (8h)
	- PPT
		- Intuitive to use
		- (Almost) everybody knows how to use it
		- Existing slide material
		- Low effort to do easy things, medium effort to do advanced things
		- Needs Microsoft PowerPoint to create and view
			- Vendor lock-in
		- Share as a file
		- Devil you know
	- Reveal.js
		- Version control
		- Scales with screen dimensions
		- Works on mobile
		- Better interactivity
		- Modern design
		- Low effort to do easy things, high effort to do advanced things
		- Needs a framework to create, a browser to use
		- Share with a link
		- PDF export possible if files are required, but clunky
		- Devil you don't know

**Comment by OleMussmann** [comment]
A manual for creating, serving, publishing and using the theme elements can be found here: https://nlesc-slides.github.io/2024-06-03_slide_manual/
