### ISSUE TITLE
Deploy slides in the right place

### ISSUE THREAD

**Issue by lyashevska** [esciencecenter-digital-skills/good-practices-in-research-software-development#22]
Deployment in the right place – preferably in the good practices in research software development repo.
There are multiple deployments with the most recent version being deployed [here](https://github.com/lyashevska/ds-cr-slides)

This relates to #18

**Comment by lyashevska** [comment]
- [ ] for [git-lesson](https://github.com/esciencecenter-digital-skills/git-lesson) this should be git-lesson-slides repo.
- [ ] for [good-practices-lesson](https://github.com/esciencecenter-digital-skills/good-practices-lesson) this should be good-practices-slides repo.
- [ ] add to the README in both repos link to the slides.

**Comment by JaroCamphuijsen** [comment]
We discussed to make one repo, using the NEBULA framework with the NLeSC reveal.js style to deploy the slides of both git and good practices lessons. This repo will contain the markdown and slides: https://github.com/esciencecenter-digital-skills/digital-skills-slides

**Comment by JaroCamphuijsen** [comment]
The PR that implements this: https://github.com/esciencecenter-digital-skills/digital-skills-slides/pull/1
