### ISSUE TITLE
A better name?

### ISSUE THREAD

**Issue by svenvanderburg** [esciencecenter-digital-skills/good-practices-in-research-software-development#4]
I'm still not superhappy with the name of the workshop, what do you think?

**Comment by svenvanderburg** [comment]
Some suggestions:
* Software engineering best practices

**Comment by mkuzak** [comment]
some more ideas

- good practices in research software
- research software skills
- reproducible research software

**Comment by svenvanderburg** [comment]
I will go for 'Good practices in research software engineering'. I hope everyone likes it.

**Comment by mkuzak** [comment]
is "engineering" necessary to include? Maybe "Good practices in research software development" or "Good practices in writing research software". I think "engineering" can make it more intimidating.
