### ISSUE TITLE
Move Documentation to the new workbench lesson

### ISSUE THREAD

**Issue by lyashevska** [esciencecenter-digital-skills/good-practices-in-research-software-development#40]

**Comment by carlosug** [comment]
finished transfer in-code documentation content: [https://github.com/esciencecenter-digital-skills/git-lesson/blob/create_lesson_content/episodes/05-documentation.md](https://github.com/esciencecenter-digital-skills/git-lesson/blob/create_lesson_content/episodes/05-documentation.md)
