### ISSUE TITLE
Suggestion for introduction text

### ISSUE THREAD

**Issue by theredgeek** [esciencecenter-digital-skills/good-practices-in-research-software-development#7]
Hello,
I am Anne (they/them), and I am a new intern. Today I was working on ideas for Tweets to promote workshops online, and I found that the description of the workshop leaves a few things unclear to the user.
The description uses a lot of important keywords, and I know the syllabus is provided, but I think it would be nice to have a little more information on what good software practices actually entail. For example, a brief description of each item in the schedule or an overview of some methods and their implementations in the description.
Kind regards

**Comment by svenvanderburg** [comment]
Thanks for your suggestion @theredgeek . Do you feel comfortable opening a PR with suggestions for changes? Otherwise I will try to pick it up in the next few weeks.

**Comment by svenvanderburg** [comment]
And I assume you refer to the description in workshop-metadata? The descriptions in this repo will only be seen by employees of the nlesc.

**Comment by svenvanderburg** [comment]
Fixed with https://github.com/esciencecenter-digital-skills/workshop-metadata/pull/91
